sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"

text_sensor:
  - platform: version
    name: "${friendly_name} ESPHome Version"

button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: diagnostic
  - platform: safe_mode
    name: "${friendly_name} Safe Mode Restart"
    entity_category: diagnostic
  - platform: factory_reset
    name: "${friendly_name} Factory Reset"
    entity_category: diagnostic
    disabled_by_default: true
